site_name: Suporte
repo_url: https://github.com/wesleyhenriques33/suporte
repo_name: Wesley Henriques - Suporte
theme:
  name: material
  logo: assets/images/logo.svg
  icon: assets/images/logo.svg
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt-BR
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to Dark mode
      primary: amber
      accent: indigo 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to Light mode   
      primary: black
      accent: indigo

plugins:
  - site-urls:
      attributes:
        - href
        - src
        - data
        - data-url
  - glightbox
  - offline
  - drawio_file
  - social
  - search:
      lang: pt
  - tags

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/wesleyhenriques.oficial
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@WesleyHenriques.Oficial
    - icon: fontawesome/brands/whatsapp
      link: https://wa.me/5547920017909
  status:
    <identifier>: <description>

extra_javascript:
  - javascripts/extra.js
  - javascripts/glightbox.min.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/glightbox.min.css

markdown_extensions:
  - smarty
  - sane_lists
  - tables
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      permalink: true
      title: Nesta página
      separator: "_"
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - admonition
  - def_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.smartsymbols
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://linktr.ee/wesleyhenriques.oficial"  target="_blank" rel="noopener">Wesley Henriques</a>