site_name: Suporte
site_url: https://suporte.wesleyhenriques.com/
repo_url: https://github.com/wesleyhenriques33/suporte
repo_name: Wesley Henriques - Suporte
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.svg
  icon: assets/images/logo.svg
  features:
    - announce.dismiss
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - search.boost
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt-BR
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to Dark mode
      primary: amber
      accent: indigo 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to Light mode   
      primary: black
      accent: indigo

plugins:
  - privacy
  - glightbox
  - search:
      lang: pt
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer
  - social:
      # enabled: !ENV [CI, false]
      cards_layout_options:
        background_color: "#ffc105"
        logo: docs/assets/images/logo.svg
  - blog:
      pagination_per_page: 5
      pagination_url_format: "{page}"
      archive_name: Arquivo
      archive_date_format: yyyy
      archive_url_format: "archive/{date}"
      archive_toc: true
      blog_toc: true
      post_date_format: full
      post_url_format: "{categories}/{slug}"
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      categories_name: Categorias
      categories_url_format: "category/{slug}"
      categories_toc: true
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tags
  - offline

hooks:
  - hooks/socialmedia.py

extra:
  analytics:
    provider: custom
    property: foobar
    feedback:
      title: Esta informação foi útil?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Sim, foi muito útil!
          data: 1
          note: >-
            Agradecemos pelo seu Feedback!!
        - icon: material/emoticon-sad-outline
          name: Não, mas pode ser melhorada.
          data: 0
          note: >- 
            Agradecemos pelo seu Feedback!! Ajude-nos a melhorar enviando informações para o email <a href="mailto:homestudio7rec@gmail.com" target="_blank" rel="mailto:homestudio7rec@gmail.com">homestudio7rec@gmail.com</a>.
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/wesleyhenriques.oficial
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@WesleyHenriques.Oficial
    - icon: fontawesome/brands/whatsapp
      link: https://wa.me/5547920017909
    - icon: simple/linktree
      link: https://linktr.ee/wesleyhenriques.oficial
  status:
    <identifier>: <description>
  consent:
    title: Consentimento de Cookies
    description: >- 
      Este site faz uso de coockies para melhor gerenciar sua performance e dados.
  generator: false

extra_javascript:
  - javascripts/extra.js
  - javascripts/glightbox.min.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/glightbox.min.css

markdown_extensions:
  - smarty
  - sane_lists
  - tables
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      permalink: true
      title: Nesta página
      separator: "-"
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - admonition
  - def_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.smartsymbols
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://linktr.ee/wesleyhenriques.oficial"  target="_blank" rel="noopener">Wesley Henriques</a>
