authors:
  wesleyhenriques:
    name: Wesley Henriques
    description: Creator
    avatar: https://ugc.production.linktr.ee/ef26f09d-90f8-42f5-a62c-42887bdb8009_Foto-Perfil-FDR.jpeg?io=true&size=avatar-v3_0
    url: https://linktr.ee/wesleyhenriques.oficial